### ISSUE TITLE
cyclic data csv

### ISSUE THREAD

**Issue by arcaldwell49** [ccoolbaugh/FloWave.US#14]
###### Enter the FloWave.US version number (e.g. v.0.2.0)
v. 0.2.2

###### What was the expected behavior? What actually happened? (Screen shots of the error may be helpful)
I was testing the software out on our own ultrasound images. The output states "Enter filename to write cyclic data (must include file extension ".csv"): cyclicPaxtonv1.csv
Data Format: PSVTime,PSV,PDVTime,PDV,EDVTime,EDV,ISVTime,ISV,MBF1,MBF2,SysTime,DiasTime,OSI,WindowTime."

However, I am not sure what each of these abbreviations mean. Also, I cannot find any documentation about these abbreviations mean. If these could be added to the wiki that would be extremely helpful.

###### What steps reproduce the problem?
Simple FloWaveUS analysis

**Comment by ccoolbaugh** [comment]
Thanks for highlighting a need for more documentation about the data summary files. I'll add a data dictionary to the wiki to describe the variable names and units

**Comment by ccoolbaugh** [comment]
I added a [data dictionary](https://github.com/ccoolbaugh/FloWave.US/wiki/4.-How-to-Use-FloWave.US#Data) to the wiki. The dictionary describes each variable, its units, and references equations used to calculate the value. 

I'm going to close this issue. Please feel free to reopen it if you have further questions related to this topic. Thanks!
