### ISSUE TITLE
FMD data analysis

### ISSUE THREAD

**Issue by mnelson88** [ccoolbaugh/FloWave.US#15]
###### Enter the FloWave.US version number (e.g. v.0.2.0)
v.0.2.2
###### What was the expected behavior? What actually happened? (Screen shots of the error may be helpful)
N/A
###### What steps reproduce the problem?
N/A
###### Other context details (e.g. computer operating system, Matlab version, ultrasound equipment, video recording equipment)
I have not had any issues with the software - I have just been exploring the program with the demo videos provided. I am interested in using this program for FMD analysis, and I was just wondering if you had any examples of FMD video to post to practice utilizing this program for data processing? We are in the process of acquiring a video capture device (we have access to the same type of ultrasound, GE Logiq) so we haven't gotten any of videos off our machine in a high enough resolution, but were just interested in learning how to process the data. I do not have experience in MatLab other than the demos provided here. Thank you.

**Comment by ccoolbaugh** [comment]
Thanks for the question about FMD analysis - I know several groups are interested in using the software for that purpose. Our research group does not do FMD experiments, but the software should work for that type of analysis. 

If you **(or anyone else)** is able to provide a FMD experiment video, I'd be happy to analyze it with the software and post as an example demo for the FloWave.US community. 

Please let me know if you are able to record a video or if you have any other questions.

**Comment by mnelson88** [comment]
Hi Crystal!

Thank you so much for getting back to me and for your willingness to help with an analysis. That would be really helpful for me. I’m hoping to get a video capture device in the mail today so I will try to run FMD with someone and send it along. I will also try to play around with it. I have some experience with other coding programs such as R, but not Mat Lab.

Megan

_______________________
Megan C. Nelson, MS, ACSM EP-C, NAPT-CPT
PhD Candidate
National Student Representative | ACSM Northwest
Department of Movement Sciences | University of Idaho

**Comment by ccoolbaugh** [comment]
No problem. It would be a big help for a lot of people if a FMD demo is available.  

Good luck with the video capture device, and be sure to check out the [Wiki](https://github.com/ccoolbaugh/FloWave.US/wiki) for more instructions and GIFs about how to use FloWave.US. I also recommend watching some of the Getting Started with Matlab videos (~ 5 mins) to get oriented to the software quickly.

**Comment by mnelson88** [comment]
Hi Crystal,

Sorry for taking so long to respond. Just had some things come up. How can I best get these video files up here - looks like in these comments a video file is not supported for upload.

Thanks!
Megan

**Comment by ccoolbaugh** [comment]
Hi Megan,

It's probably easiest to email me the video file. My email is listed in the corresponding author info in the [Journal of Applied Physiology](http://jap.physiology.org/content/121/4/849 "Journal of Applied Physiology Reference") article. 

If the file is too big to send as an attachment, you could fork the Github repo and submit a pull request with the file added to the Demo Folder. Let me know if you need some help with this step, and I can send some tutorial links for using Github. 

Thanks,
Crystal
